# split

In [2]:
import numpy as np

In [4]:
a = np.arange(1,13).reshape(4,3)

In [5]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.split(a,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [35]:
np.split(a,2)[0] # first portion of split

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.split(a,2)[1] # second portion of split

array([[ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.split(a,2,axis=0) # splits row wise

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [38]:
np.split(a,3,axis =1) # splits column wise

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

# concatenate

In [39]:
b = np.arange(13,25).reshape(4,3)

In [40]:
b

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [41]:
np.concatenate((a,b)) # adds row wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [42]:
np.concatenate((a,b), axis = 0)  # same as above


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [43]:
np.concatenate((a,b),axis =1) # adds column wise

array([[ 1,  2,  3, 13, 14, 15],
       [ 4,  5,  6, 16, 17, 18],
       [ 7,  8,  9, 19, 20, 21],
       [10, 11, 12, 22, 23, 24]])

# Tile

In [44]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
np.tile(a,2)

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [46]:
np.tile(a,(2,1)) #this function does not accept axis argument

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
np.tile(a,(1,2))

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [48]:
np.tile(a,(2,3))

array([[ 1,  2,  3,  1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12, 10, 11, 12],
       [ 1,  2,  3,  1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12, 10, 11, 12]])

# Repeat

In [49]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
np.repeat(a,2,axis =1)

array([[ 1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6],
       [ 7,  7,  8,  8,  9,  9],
       [10, 10, 11, 11, 12, 12]])

In [51]:
np.repeat(a,3, axis = 0)

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  5,  6],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [10, 11, 12],
       [10, 11, 12]])